AWSTemplateFormatVersion: '2010-09-09'
Description: Create an EC2 instance

Resources:
  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      ImageId: ami-023a307f3d27ea427  # Replace with the AMI ID you want to use
      KeyName: 9.15.devops  # Replace with your EC2 key pair name
      SecurityGroups:
        - Ref: MySecurityGroup
      AvailabilityZone: ap-south-1a  # Choose your preferred availability zone

  MySecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'Allow SSH access'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: '0.0.0.0/0'  # Allow SSH from anywhere (be cautious with this)
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: '0.0.0.0/0'  # Allow SSH from anywhere (be cautious with this)
